name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build Docker image
      run: docker build --build-arg API_EXTERNAL_ACCESS_DATA_URL=${{ secrets.API_EXTERNAL_ACCESS_DATA_URL }} --build-arg API_EXTERNAL_CACHE_URL=${{ secrets.API_EXTERNAL_CACHE_URL }} --build-arg RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} --build-arg RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }} --build-arg RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }} --build-arg RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }} -t $DOCKER_USERNAME/data-manager .
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      
    - name: Push Docker image
      run: docker push $DOCKER_USERNAME/data-manager
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
